ARG GO_VERSION=1.21.0

FROM golang:${GO_VERSION} AS builder

WORKDIR /app
COPY go.mod go.sum /app/
RUN go mod download

COPY ./cmd/eventual /app/cmd/eventual
COPY ./internal /app/internal
RUN CGO_ENABLED=0 go build --trimpath -o /bin/eventual ./cmd/eventual

FROM gcr.io/distroless/static AS production

COPY --from=builder /bin/eventual /

EXPOSE 8080
USER nonroot
ENTRYPOINT ["/eventual"]
