ARG NODE_VERSION=18
FROM node:${NODE_VERSION} as builder

ARG BACKEND_URL="https://eventual-server.fly.dev"

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install --omit="dev"
COPY . .

ENV REACT_APP_BACKEND_URL=${BACKEND_URL}
RUN npm run build

FROM nginxinc/nginx-unprivileged as nginx

COPY --chown=nginx:nginx nginx.client.conf /etc/nginx/nginx.conf

COPY --from=builder /app/build/ /www/data/

EXPOSE 8080

USER nginx
ENTRYPOINT ["/usr/sbin/nginx", "-g", "daemon off;"]
