# fly.toml app configuration file generated for eventual-client on 2023-09-04T11:15:22-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "eventual-client"
primary_region = "dfw"

[build]
  dockerfile = "./Dockerfile.client"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
